name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4

      - name: Cache build
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache
            build/
          key: ${{ runner.os }}-build-${{ hashFiles('**/Makefile') }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Run make
        run: |
          make
          make test

      - name: Upload build logs
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: build-logs
          path: |
            build.log
            test-report.xml
