name: CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build & Test (Linux)
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies (raylib via PPA)
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y ppa:texus/raylib
          sudo apt-get update
          sudo apt-get install -y \
            build-essential cmake ninja-build git pkg-config \
            libraylib5-dev \
            xorg-dev libglu1-mesa-dev libxinerama-dev libxcursor-dev libxrandr-dev libxi-dev

      - name: Clean build dir
        run: rm -rf build

      - name: Configure (CMake + Ninja)
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build -j

      - name: Test (CTest)
        run: |
          if [ -f build/CTestTestfile.cmake ] && grep -q 'add_test' build/CTestTestfile.cmake; then
            ctest --test-dir build --output-on-failure --output-junit test-report.xml
          else
            echo "No tests defined. Skipping ctest."
            printf '<testsuite name="no-tests"/>\n' > test-report.xml
          fi

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test-report.xml
