name: CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build & Test (Linux)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Prepare vcpkg cache dir
        run: |
          mkdir -p ~/.cache/vcpkg/archives
          echo "VCPKG_DEFAULT_BINARY_CACHE=$HOME/.cache/vcpkg/archives" >> $GITHUB_ENV

      - name: Cache vcpkg binary cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/vcpkg/archives
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('vcpkg.json', 'vcpkg-configuration.json') }}
          restore-keys: ${{ runner.os }}-vcpkg-

      # <-- This is the crucial bit for GLFW on Linux
      - name: Install GLFW/X11 prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libxinerama-dev \
            libxcursor-dev \
            xorg-dev \
            libglu1-mesa-dev \
            pkg-config

      - name: Install base build tools
        run: |
          sudo apt-get install -y cmake ninja-build git

      - name: Bootstrap vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          git -C vcpkg pull --ff-only
          ./vcpkg/bootstrap-vcpkg.sh
        env:
          VCPKG_FORCE_SYSTEM_BINARIES: 1

      - name: Install raylib via vcpkg
        run: ./vcpkg/vcpkg install raylib:x64-linux

      - name: Configure (CMake)
        run: |
          cmake -S . -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_TOOLCHAIN_FILE=${GITHUB_WORKSPACE}/vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: Build
        run: cmake --build build --config Release -j

      - name: Test (CTest)
        run: |
          if [ -f build/CTestTestfile.cmake ] && grep -q 'add_test' build/CTestTestfile.cmake; then
            ctest --test-dir build --output-on-failure --output-junit test-report.xml
          else
            echo "No tests defined. Skipping ctest."
            touch test-report.xml
          fi

      - name: Show vcpkg glfw logs on failure
        if: failure()
        run: |
          find vcpkg/buildtrees/glfw3 -maxdepth 1 -type f -name 'config-*.log' -print -exec sed -n '1,200p' {} \;

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test-report.xml
